[package]
name = "dupekit"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
dupekit-core = { path = "../core" }
dupekit-storage = { path = "../storage" }
iced.workspace = true
rfd.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

